# Generated by Django 2.2.5 on 2019-11-22 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='before',
            field=models.TextField(verbose_name='Before Link'),
        ),
    ]
