# Generated by Django 3.0.6 on 2020-05-14 03:49

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterField(
            model_name='category',
            name='desc',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='course',
            name='intro_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Course Text introduction'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='desc',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='user',
            name='about',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterUniqueTogether(
            name='rel',
            unique_together={('course', 'student')},
        ),
    ]
