# Generated by Django 2.2.5 on 2019-11-23 01:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20191122_2221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsteller',
            options={'verbose_name': 'News Teller Subscriber', 'verbose_name_plural': 'NewsTeller Subscriber'},
        ),
        migrations.AlterModelOptions(
            name='newsteller_emails',
            options={'verbose_name': 'NewsTeller Email', 'verbose_name_plural': 'NewsTeller Emails'},
        ),
        migrations.AddField(
            model_name='student_study_course',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date'),
            preserve_default=False,
        ),
    ]
