# Generated by Django 2.2.5 on 2019-11-23 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20191123_0123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student_study_course',
            options={'ordering': ['date'], 'verbose_name': 'Enrollment', 'verbose_name_plural': 'Enrollments'},
        ),
    ]
